// Code generated by Kitex v0.10.3. DO NOT EDIT.

package couponrecordservice

import (
	"context"
	coupon_record "github.com/Tzz1194593491/coupon_server/kitex_gen/com/tang/coupon_server/coupon_record"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendCoupon(ctx context.Context, req *coupon_record.CouponRecordSendReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordSendResp, err error)
	GetCouponRecordList(ctx context.Context, req *coupon_record.CouponRecordListReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordListResp, err error)
	UseCoupon(ctx context.Context, req *coupon_record.CouponRecordUsedReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordUsedResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCouponRecordServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCouponRecordServiceClient struct {
	*kClient
}

func (p *kCouponRecordServiceClient) SendCoupon(ctx context.Context, req *coupon_record.CouponRecordSendReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordSendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendCoupon(ctx, req)
}

func (p *kCouponRecordServiceClient) GetCouponRecordList(ctx context.Context, req *coupon_record.CouponRecordListReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCouponRecordList(ctx, req)
}

func (p *kCouponRecordServiceClient) UseCoupon(ctx context.Context, req *coupon_record.CouponRecordUsedReq, callOptions ...callopt.Option) (r *coupon_record.CouponRecordUsedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UseCoupon(ctx, req)
}
